spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/herma88wan/centralized-configuration-example.git
          search-paths: 'configurations/{application}'
          clone-on-start: true
          force-pull: true
logging.level.org.springframework.web: TRACE
server:
  port: 8888